#!/bin/sh
LC_ALL=C
echo "running precommit hook" 
# Select files to format
GITFILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')
GITFILESq=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')
[ -z "$GITFILES" ] && exit 0
# Format all selected files
echo "$GITFILES" 
echo "$GITFILESq" 
xargs dotnet-format --include  $GITFILES
# Add back the modified files to staging
echo "$GITFILES" | xargs git add
exit 0

